// Autogenerated
export default [
  {
    "name": "/web/api/chart-settings/",
    "pathname": "/web/api/chart-settings.api.js"
  },
  {
    "name": "/web/api/data/",
    "pathname": "/web/api/data.api.js"
  },
  {
    "name": "/web/api/sync/",
    "pathname": "/web/api/sync.api.js"
  },
  {
    "name": "/web/api/user-settings/",
    "pathname": "/web/api/user-settings.api.js"
  },
  {
    "name": "/web/charts/edit/",
    "pathname": "/web/charts/edit.html.js"
  },
  {
    "name": "/web/charts/",
    "pathname": "/web/charts.html.js"
  },
  {
    "name": "/web/css/index.v4.css",
    "pathname": "/web/css/index.v4.css"
  },
  {
    "name": "/web/entries/edit/",
    "pathname": "/web/entries/edit.html.js"
  },
  {
    "name": "/web/entries/",
    "pathname": "/web/entries.html.js"
  },
  {
    "name": "/web/entry-points.js",
    "pathname": "/web/entry-points.js"
  },
  {
    "name": "/web/index/",
    "pathname": "/web/index.html.js"
  },
  {
    "name": "/web/js/charts-page.js",
    "pathname": "/web/js/charts-page.js"
  },
  {
    "name": "/web/js/charts.shared.js",
    "pathname": "/web/js/charts.shared.js"
  },
  {
    "name": "/web/js/dom-utils.js",
    "pathname": "/web/js/dom-utils.js"
  },
  {
    "name": "/web/js/elastic-textarea.js",
    "pathname": "/web/js/elastic-textarea.js"
  },
  {
    "name": "/web/js/lib/chart.min.js",
    "pathname": "/web/js/lib/chart.min.js"
  },
  {
    "name": "/web/js/main.js",
    "pathname": "/web/js/main.js"
  },
  {
    "name": "/web/js/snack-bar.js",
    "pathname": "/web/js/snack-bar.js"
  },
  {
    "name": "/web/service-worker/js-loader.js",
    "pathname": "/web/service-worker/js-loader.js"
  },
  {
    "name": "/web/service-worker/route-handling.js",
    "pathname": "/web/service-worker/route-handling.js"
  },
  {
    "name": "/web/settings.js",
    "pathname": "/web/settings.js"
  },
  {
    "name": "/web/sw.js",
    "pathname": "/web/sw.js"
  },
  {
    "name": "/web/user-settings/edit/",
    "pathname": "/web/user-settings/edit.html.js"
  }
]