// Autogenerated
const links : string[] = ['/web/_layout.html.js','/web/user-settings/edit.html.js','/web/entries.html.js','/web/charts/edit.html.js','/web/entries/edit.html.js','/web/charts.html.js','/web/index.html.js','/web/js/charts-page.v3.js','/web/js/elastic-textarea.js','/web/js/utils.v3.js','/web/js/dom-utils.js','/web/js/snack-bar.js','/web/js/main.js','/web/js/charts-shared.v3.js']
export default links
